.apex/src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>F</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PicklistController.cls
public with sharing class PicklistController {

	@AuraEnabled(cacheable=true)
	public static List<Map<String, String>> getFamilyValues(){
		list<Map<String, String>> familyValues= new List<Map<String, String>>();
		Schema.DescribeFieldResult fieldResult = Product__c.Family__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		Integer i = 1;
		for(Schema.PicklistEntry pickListVal : ple){
			familyValues.add(new Map<String, String>{
				'Id' => String.valueOf(i),
				'Value' => pickListVal.getLabel()
			});
			i++;
		}
		return familyValues;
	}

	@AuraEnabled(cacheable=true)
	public static List<Map<String, String>> getTypeValues(){
		List<Map<String, String>> typeValues= new List<Map<String, String>>();
		Schema.DescribeFieldResult fieldResult = Product__c.Type__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		Integer i = 1;
		for(Schema.PicklistEntry pickListVal : ple){
			typeValues.add(new Map<String, String>{
				'Id' => String.valueOf(i),
				'Value' => pickListVal.getLabel()
			});
			i++;
		}
		return typeValues;
	}

}