.apex/src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>F</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/src/classes/ProductController.cls
public with sharing class ProductController {

	@AuraEnabled(cacheable=true)
	public static List<Product__c> getProductList(String searchKey) {
		String key = '%' + searchKey + '%';
		return [
				SELECT Id, Name, Description__c, Family__c, Type__c, Price__c
				FROM Product__c
				WHERE Name LIKE :key
				LIMIT 20
		];
	}

	@AuraEnabled(cacheable=true)
	public static Product__c getProductDetail(String prodId) {
		return [
				SELECT Id, Name, Description__c, Family__c, Type__c, Image__c, Price__c
				FROM Product__c
				WHERE Id =:prodId
		];
	}

	@AuraEnabled
	public static void createNewProduct(Map<String, Object> product) {
		try {
			Product__c newProduct = new Product__c(
					Name = (String)product.get('Name'),
					Description__c = (String)product.get('Description'),
					Type__c = (String)product.get('Type'),
					Family__c = (String)product.get('Family'),
					Image__c = (String)product.get('Image'),
					Price__c = Integer.valueOf(product.get('Price'))
			);
			insert newProduct;
			System.debug('Successfully created product');
		} catch (DmlException e) {
			System.debug('An unexpected error has occurred: ' + e.getMessage());
		}

	}
}