src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>TotalPrice</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalProductCount__c</fullName>
        <label>TotalProductCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrdItem__c.object
<CustomObject>
    <fields>
        <fullName>OrderId__c</fullName>
        <label>OrderId</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>OrdItems</relationshipLabel>
        <relationshipName>OrdItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductId__c</fullName>
        <label>ProductId</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>OrdItems</relationshipLabel>
        <relationshipName>OrdItems</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OrdItem</label>
    <nameField>
        <label>OrdItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrdItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OrderController.cls
public with sharing class OrderController {

	@AuraEnabled
	public static void createOrder(String accId, List<Map<String, Object>> items) {
		try {
			Order__c order = new Order__c(Name='NewOrder', AccountId__c=accId, TotalPrice__c = 0, TotalProductCount__c = 0);
			insert order;

			ID orderId = order.Id;
			List<OrdItem__c> orderItemsToInsert = new List<OrdItem__c>();
			for(Map<String, Object> item: items) {
				OrdItem__c orderItem = new OrdItem__c(
					OrderId__c = orderId,
					ProductId__c = (String)item.get('Id'),
					Quantity__c = Integer.valueOf(item.get('Quantity')),
					Price__c = Integer.valueOf(item.get('Price')) * Integer.valueOf(item.get('Quantity'))
				);
				orderItemsToInsert.add(orderItem);
			}
			insert orderItemsToInsert;
			System.debug('Successfully inserted');

		} catch (DmlException e) {
			System.debug('An unexpected error has occurred: ' + e.getMessage());
		}
	}
}