src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>TotalPrice</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalProductCount__c</fullName>
        <label>TotalProductCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrdItem__c.object
<CustomObject>
    <fields>
        <fullName>OrderId__c</fullName>
        <label>OrderId</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>OrdItems</relationshipLabel>
        <relationshipName>OrdItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductId__c</fullName>
        <label>ProductId</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>OrdItems</relationshipLabel>
        <relationshipName>OrdItems</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OrdItem</label>
    <nameField>
        <label>OrdItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrdItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

.apex/src/classes/OrderControllerTest.cls
@IsTest
public class OrderControllerTest {
	@IsTest
	static void test_createOrder() {
		// Set up test data set
		String accId = '0013V0000079GT5QAM';
		List<Map<String, Object>> items = new List<Map<String, Object>>();
		items.add(new Map<String, Object>{
			'Id' => 'a013V000003RFzCQAW',
			'Name' => 'Laptop White Xiaomi',
			'Price' => 400,
			'Quantity' => 2
		});

		items.add(new Map<String, Object>{
			'Id' => 'a013V000003QkYRQA0',
			'Name' => 'Keyboard Black',
			'Price' => 20,
			'Quantity' => 3
		});

		// Execute code with test data
		OrderController.createOrder(accId, items);  // call
	}

	@IsTest
	static void test_triggerOnOrdItems() {
		// Set up test data set
		String accId = '0013V0000079GT5QAM';
		String prodId1 = 'a013V000003RFzCQAW';
		String prodId2 = 'a013V000003QkYRQA0';
		List<Map<String, Object>> items = new List<Map<String, Object>>();
		items.add(new Map<String, Object>{
			'Id' => prodId1,
			'Name' => 'Laptop White Xiaomi',
			'Price' => 400,
			'Quantity' => 1
		});

		items.add(new Map<String, Object>{
			'Id' => prodId2,
			'Name' => 'Keyboard Black',
			'Price' => 20,
			'Quantity' => 2
		});

		// Execute code with test data
		OrderController.createOrder(accId, items);  // call

		Order__c order = [SELECT Id, TotalPrice__c, TotalProductCount__c, (SELECT Id, Price__c, Quantity__c FROM OrdItems__r WHERE ProductId__c =:prodId1) FROM Order__c];

		System.assertEquals(440, order.TotalPrice__c);
		System.assertEquals(3, order.TotalProductCount__c);
	}

}